import { RiskType } from '@/types'

export const DEFAULT_CATALOG: RiskType[] = [
  {
    id: '1',
    name: 'Buraco',
    iconName: 'AlertCircle',
    baseWeight: 2,
    category: 'Via',
    description: 'Irregularidades estruturais ou buracos na pista',
  },
  {
    id: '2',
    name: 'Rotatória',
    iconName: 'CircleDashed',
    baseWeight: 1,
    category: 'Infraestrutura',
    description: 'Interseção em círculo exigindo redução de velocidade',
  },
  {
    id: '3',
    name: 'Polícia',
    iconName: 'ShieldAlert',
    baseWeight: 1,
    category: 'Segurança',
    description: 'Posto policial ou fiscalização na rodovia',
  },
  {
    id: '4',
    name: 'Cruzamento',
    iconName: 'Crosshair',
    baseWeight: 3,
    category: 'Infraestrutura',
    description: 'Interseção perigosa com vias secundárias',
  },
  {
    id: '5',
    name: 'Curva Perigosa',
    iconName: 'TrendingUp',
    baseWeight: 4,
    category: 'Via',
    description: 'Curva acentuada com risco de tombamento ou saída de pista',
  },
  {
    id: '6',
    name: 'Animal na Pista',
    iconName: 'Bird',
    baseWeight: 4,
    category: 'Fauna',
    description: 'Presença de animais silvestres ou de grande porte',
  },
  {
    id: '7',
    name: 'Neblina',
    iconName: 'CloudFog',
    baseWeight: 3,
    category: 'Clima',
    description: 'Baixa visibilidade devido a condições climáticas',
  },
  {
    id: '8',
    name: 'Chuva Forte',
    iconName: 'CloudRain',
    baseWeight: 4,
    category: 'Clima',
    description: 'Risco de aquaplanagem e baixa visibilidade',
  },
  {
    id: '9',
    name: 'Trânsito',
    iconName: 'CarFront',
    baseWeight: 2,
    category: 'Trânsito',
    description: 'Congestionamento ou lentidão na via',
  },
  {
    id: '10',
    name: 'Acidente',
    iconName: 'Octagon',
    baseWeight: 4,
    category: 'Trânsito',
    description: 'Ocorrência de colisão ou interrupção grave no trajeto',
  },
]

export const LEVEL_THRESHOLDS = {
  BAIXO: 10,
  MEDIO: 30,
  ALTO: 60,
}
