import { RiskType } from '@/types'

export const DEFAULT_CATALOG: RiskType[] = [
  {
    id: '1',
    name: 'Buracos e deformações no pavimento',
    iconName: 'CircleDashed',
    baseWeight: 3,
    category: 'Via',
  },
  { id: '2', name: 'Pista escorregadia', iconName: 'Waves', baseWeight: 4, category: 'Via' },
  {
    id: '3',
    name: 'Sinalização horizontal apagada',
    iconName: 'Minus',
    baseWeight: 2,
    category: 'Sinalização',
  },
  {
    id: '4',
    name: 'Sinalização vertical insuficiente',
    iconName: 'Signpost',
    baseWeight: 2,
    category: 'Sinalização',
  },
  { id: '5', name: 'Curvas fechadas', iconName: 'TrendingUp', baseWeight: 3, category: 'Via' },
  {
    id: '6',
    name: 'Declives e aclives acentuados',
    iconName: 'TrendingDown',
    baseWeight: 3,
    category: 'Via',
  },
  { id: '7', name: 'Trechos com neblina', iconName: 'CloudFog', baseWeight: 3, category: 'Clima' },
  { id: '8', name: 'Aquaplanagem', iconName: 'Droplets', baseWeight: 4, category: 'Clima' },
  {
    id: '9',
    name: 'Acostamento inexistente ou estreito',
    iconName: 'ArrowRightToLine',
    baseWeight: 3,
    category: 'Infraestrutura',
  },
  {
    id: '10',
    name: 'Acostamento degradado',
    iconName: 'TriangleAlert',
    baseWeight: 2,
    category: 'Infraestrutura',
  },
  { id: '11', name: 'Pontes', iconName: 'Waypoints', baseWeight: 2, category: 'Infraestrutura' },
  {
    id: '12',
    name: 'Interseções e retornos perigosos',
    iconName: 'Shuffle',
    baseWeight: 4,
    category: 'Via',
  },
  {
    id: '13',
    name: 'Entradas e saídas de veículos pesados',
    iconName: 'Truck',
    baseWeight: 3,
    category: 'Trânsito',
  },
  {
    id: '14',
    name: 'Ultrapassagens perigosas',
    iconName: 'CarFront',
    baseWeight: 4,
    category: 'Trânsito',
  },
  { id: '15', name: 'Animais na pista', iconName: 'Bird', baseWeight: 4, category: 'Fauna' },
  {
    id: '16',
    name: 'Travessia de pedestres',
    iconName: 'User',
    baseWeight: 3,
    category: 'Trânsito',
  },
  {
    id: '17',
    name: 'Áreas urbanizadas',
    iconName: 'Building',
    baseWeight: 2,
    category: 'Trânsito',
  },
  {
    id: '18',
    name: 'Falha de comunicação (sinal de celular)',
    iconName: 'WifiOff',
    baseWeight: 2,
    category: 'Infraestrutura',
  },
]

export const LEVEL_THRESHOLDS = {
  BAIXO: 10,
  MEDIO: 30,
  ALTO: 60,
}
